
name: Build Graph Node Image
on:
  push:
    branches:
      # Push events to every branch adhering SemVer like v1.0.0-alpha.1
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-**'
      - user/apehota/build-docker-image
  workflow_dispatch:
    inputs:
      image_tag:
        required: true
        type: string
        description: 'Image tag'

env:
  DOCKER_BUILDKIT: "1"
  BRANCH: ${{ github.ref_name }}
  IMAGE_TAG: ${{ github.event.inputs.image_tag }}

permissions:
  contents: write
  packages: write

jobs:
  build_image:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}
      - uses: ./.github/actions/build-docker-image
        with:
#          image_tag: ${{ env.IMAGE_TAG || env.BRANCH }}
          image_tag: "test-v1"
          github_sha: ${{ github.sha }}
          github_repo: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: "docker/Dockerfile"
